#!/bin/bash

#
# Ubiquitous Moodle
#
# @author Luke Carrier <luke@carrier.im>
# @copyright 2016 Luke Carrier
#

install_master=''
install_minion=''
root=''
eval set -- "$(getopt -o "air:" --long "master:,minion:,root:" -- "$@")"
while true; do
    case "$1" in
        -a|--master) install_master="$2" ; shift 2 ;;
        -i|--minion) install_minion="$2" ; shift 2 ;;
        -r|--root  ) root="$2"           ; shift 2 ;;
        *          ) break               ;         ;;
    esac
done

set -euo pipefail
IFS=$'\n\t'

export DEBIAN_FRONTEND='noninteractive'

SALTSTACK_GPG_KEY='https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub'
SALTSTACK_SOURCES='deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main'
SALTSTACK_SOURCES_LIST='/etc/apt/sources.list.d/saltstack.list'

SALTSTACK_GPG_KEY="http://repo.saltstack.com/yum/redhat/7/x86_64/latest/SALTSTACK-GPG-KEY.pub"
SALTSTACK_REPO="http://repo.saltstack.com/yum/redhat/7/x86_64/saltstack-rhel7.repo"

echo 'installing saltstack GPG key...'
curl -s "$SALTSTACK_GPG_KEY" | sudo apt-key add -

echo 'installing saltstack APT repository...'
echo "$SALTSTACK_SOURCES" >"$SALTSTACK_SOURCES_LIST"

if [ -n "$install_master" ]; then
    echo 'installing Salt master...'
    apt-get install -y salt-master >/dev/null

    echo 'installing configuration...'
    mkdir -p /etc/salt/pki/master/minions
    cp "${root}/master" /etc/salt/master
    cp "${root}/master.pem" "${root}/master.pub" /etc/salt/pki/master
    minions=($(echo $install_master | tr ',' $'\n'))
    for minion in "${minions[@]}"; do
        echo "preseeding master with minion key ${minion}..."
        cp "${root}/minions/${minion}.pub" "/etc/salt/pki/master/minions/${minion}"
    done

    echo 'enabling and starting master daemon...'
    systemctl enable salt-master 2>/dev/null
    systemctl start salt-master
fi

if [ -n "$install_minion" ]; then
    echo 'installing Salt minion...'
    apt-get install -y salt-minion >/dev/null

    echo 'installing minion configuration and keys...'
    cp "${root}/minions/${install_minion}" /etc/salt/minion
    cp "${root}/minions/${install_minion}.pem" /etc/salt/pki/minion/minion.pem
    cp "${root}/minions/${install_minion}.pub" /etc/salt/pki/minion/minion.pub

    echo 'preseeding minion with master key...'
    cp "${root}/master.pub" /etc/salt/pki/minion/minion_master.pub

    echo 'enabling and starting minion daemon...'
    systemctl enable salt-minion 2>/dev/null
    systemctl start salt-minion
fi
