#!/usr/bin/env ruby

#
# Ubiquitous Moodle
#
# @author Luke Carrier <luke.carrier@floream.com>
# @copyright 2015 Floream Limited
#

enable_cmd  = "sudo systemctl start firewalld && sudo systemctl enable firewalld"
add_svc_cmd = "sudo firewall-cmd --permanent --zone=public --add-service="
reload_cmd  = "sudo firewall-cmd --reload"

rules = {
  "salt"                  => ["ssh", "salt-master"],
  "app-debug-1"           => ["ssh", "http"],
  "db-1"                  => ["ssh", "postgresql"],
  "mail-debug"            => ["ssh", "mailcatcher"],
  "selenium-hub"          => ["ssh", "selenium-hub"],
  "selenium-node-chrome"  => ["ssh", "x11vnc"],
  "selenium-node-firefox" => ["ssh", "x11vnc"],
}

rules.each do |vm, services|
  puts "fixing #{vm}..."
  cmd =  "#{enable_cmd}"
  services.each {|service| cmd << " && #{add_svc_cmd}#{service}"}
  cmd << " && #{reload_cmd}"

  system("vagrant", "ssh", vm, "--command", cmd)
end
