#!/bin/bash

#
# Ubiquitous Moodle
#
# @author Luke Carrier <luke@carrier.im>
# @copyright 2018 The Ubiquitous Authors
#

export UBIQUITOUS_PREFIX="/usr/local/ubiquitous"
export UBIQUITOUS_BIN="${UBIQUITOUS_PREFIX}/bin"
export UBIQUITOUS_ETC="${UBIQUITOUS_PREFIX}/etc"
export UBIQUITOUS_FLAG="${UBIQUITOUS_ETC}/ubiquitous-has-%s"
export UBIQUITOUS_PLATFORMS="${UBIQUITOUS_PREFIX}/etc/ubiquitous-platforms"

export UBIQUITOUS_RELEASES_DIR="%s/releases"
export UBIQUITOUS_CURRENT_LINK="%s/current"
