#!/bin/bash

# Configure a Salt master
#
# Install Salt using Salt Bootstrap, then configure the minion with all of the
# required options and targeting grains.
#
# Example:
#     $ ./salt-minion.sh \
#             -m salt-master0.mgmt.avadolearning.net -e lp \
#             -i lp-load-web0 -n prod -r admin -r moodle-web

master=''
environment=''
grains_environment=''
grains_roles=()
salt_config_file=/etc/salt/minion.d/local.conf
salt_grains_file=/etc/salt/grains
salt_bootstrap=1

while true; do
    case "$1" in
        -m|--master)
            master="$2"
            shift 2
            ;;
        -e|--environment)
            environment="$2"
            shift 2
            ;;
        -i|--id)
            id="$2"
            shift 2
            ;;
        -n|--grain-environment)
            grains_environment="$2"
            shift 2
            ;;
        -r|--grain-role)
            grains_roles+=("$2")
            shift 2
            ;;
        -c|--salt-config-file)
            salt_config_file="$2"
            shift 2
            ;;
        -g|--salt-grains-file)
            salt_grains_file="$2"
            shift 2
            ;;
        -s|--salt-skip-install)
            salt_bootstrap=0
            shift 1
            ;;
        *)
            break
            ;;
    esac
done

set -euo pipefail
IFS=$'\n\t'

echo 'Installing Salt minion via Salt Bootstrap...'
export DEBIAN_FRONTEND=noninteractive
if [ $salt_bootstrap -ne 0 ]; then
    curl -qsLS https://bootstrap.saltstack.com | sh -s -- -x python3 >/dev/null
fi

echo 'Writing configuration...'
salt_config="master: ${master}\n"
if [ -n "$environment" ]; then
    salt_config+="saltenv: ${environment}\n"
fi
if [ -n "$id" ]; then
    salt_config+="id: ${id}\n"
fi
echo -e "$salt_config" >"$salt_config_file"

echo 'Writing grains...'
salt_grains="environment: ${grains_environment}\n"
salt_grains+="roles:\n"
for role in "${grains_roles[@]}"; do
    salt_grains+="  - ${role}\n"
done
echo -e "$salt_grains" >"$salt_grains_file"

echo 'Restarting Salt...'
systemctl restart salt-minion
